remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false


title: "GreenTrax Expense Tracker"
description: "Monthly expense tracker that allows the user to track montly spending habits."
author:
  name: "Zac Ramsey"


  copyright: true
