remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "GreenTrax Expense Tracker"
description: "Monthly expense tracker that allows the user to track montly spending habits."
author:
  name: "Zac Ramsey"

# Do not change the following line.
  copyright: true
